config/routes.rb
Rails.application.routes.draw do
  resources :quotes do
    member do 
      post "post_to_twitter"
    end
  end

  root 'quotes#index'

end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id                :integer          not null, primary key
#  author            :string
#  quote             :text
#  mood              :integer
#  quote_source      :text
#  processed_quote   :text
#  posted_to_twitter :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_quotes_on_mood  (mood)
#

class Quote < ActiveRecord::Base
  
  # lib/twitter_poster
  include  TwitterPoster

  validates :author, :quote, :mood, :quote_source, :presence => true
  validates :mood, :inclusion =>  {:in => [1,2,3]}

  validates :quote, length: { :maximum =>  140}

  before_save :process_quote

  def self.mood_counts
    all.group(:mood).count
  end

  def quote=(v)
    self[:quote] = v.to_s.encode('UTF-8', invalid: :replace, undef: :replace, replace: '')
  end

  private
  def process_quote
    self[:processed_quote] = quote.to_s.first_and_last_char_of_each_word_upcased
    # new or updated
    self[:posted_to_twitter] = false
    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :post_to_twitter]

  # GET /quotes
  def index
    params[:q]||={}
    # ransack misbehaving, temporary fix
    search = ["%", params[:q][:quote_cont_or_author_cont_or_quote_source_cont].to_s, "%"].join
    @quotes = Quote.where("LOWER(quote) LIKE :search OR LOWER(author) LIKE :search OR LOWER(quote_source) LIKE :search", search: search )
    remaining_params = params[:q].except("quote_cont_or_author_cont_or_quote_source_cont")
      
    @quotes = @quotes.search(remaining_params)
    smart_listing_create(:quotes_smart_listing, @quotes.result,
    partial: "quotes/list",
    default_sort: {id: "desc"},
    remote: true
    )
    render :action => "index", :layout => "application"
  end

  # GET /quotes/1
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to @quote, notice: 'Quote was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quotes/1
  def update
    if @quote.update(quote_params)
      redirect_to @quote, notice: 'Quote was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quotes/1
  def destroy
    @quote.destroy
    redirect_to quotes_url, notice: 'Quote was successfully destroyed.'
  end


  def post_to_twitter
    if @quote.posted_to_twitter
      redirect_to :back, alert: 'Quote already posted to twitter.'
    else
      begin
        @quote.post_quote_to_twitter!
        Quote.where(id: @quote.id).update_all(posted_to_twitter: true)        
        redirect_to :back, notice: 'Quote successfully posted to twitter.'
      rescue Exception => e
        redirect_to :back, alert: e.message
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quote_params
      params.require(:quote).permit(:author, :quote, :mood, :quote_source)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg.html_safe, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def mood_display(mood)
     case mood.to_i
     when 1
      content_tag "b", fa_icon("smile-o 2x",  class: "text-info")
     when 2
       content_tag "b",  fa_icon("meh-o  2x",  class: "text-inverse")
     when 3             
       content_tag "b",  fa_icon("frown-o  2x", class: "text-danger")
     else
      mood
     end
  end


  def mood_count_display(mood, count)
     content_tag "span",  mood_display(mood) + "(#{count})"
  end

  def mood_select_options
    [
      [fa_icon("smile-o 2x",  text:'Happy', class: "text-info"), 1],
      [fa_icon("meh-o  2x",  text:'Meh', class: "text-inverse"), 2],
      [fa_icon("frown-o  2x",text:'Unhappy', class: "text-danger"), 3]
    ]
  end

  def date_format d
    d.strftime("%F") if d
  end
  alias :df :date_format

  def datetime_format d
    d.strftime("%F %H:%M") if d
  end
  alias :dtf :datetime_format

  #panel and form actions
  def back_link(text, path, styleclass='', options={})
    link_to fa_icon('caret-square-o-left', :text => text) , path, options.merge(:class => "btn btn-default #{styleclass}")
  end

  def home_link(text, path, styleclass='', options={})
    link_to fa_icon('home', :text => text) , path, options.merge(:class => "btn btn-default #{styleclass}")
  end

  def trash_link(text, path, styleclass='', options={})
    link_to fa_icon('trash-o', :text => text), path, options.merge(:method => :delete, :class => "btn btn-warning #{styleclass}", :data => {:confirm => "Are you sure you want to permanently remove this?" })
  end

  def new_link(text, path, styleclass='', options={})
    link_to fa_icon('plus', :text => text) , path, options.merge(:class => "btn btn-success #{styleclass}")
  end

  def edit_link(text, path, styleclass='', options={})
    link_to fa_icon('pencil', :text => text) , path, options.merge(:class => "btn btn-primary #{styleclass}")
  end

  def view_link(text, path, styleclass='', options={})
    link_to fa_icon('eye', :text => text) , path, options.merge(:class => "btn btn-primary #{styleclass}")
  end

    def submit_options(extra={})
    {"class" => "btn  btn-primary btn-lg", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i> Please wait..."}.merge(extra)
  end

  def html_submit(content=fa_icon('save', :text => "Save"), extra={})
    content_tag "button", content.html_safe,  submit_options(extra)
  end

  def yesno(value,yes_text="Yes", no_text="No", yes_label_class="label label-success", no_label_class="label label-warning" )
    if value
      content_tag(:span, fa_icon("check-square", text: yes_text), class: yes_label_class )
    else
      content_tag(:span, fa_icon("square-o", text:no_text), class: no_label_class)
    end
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TarifficTakeHomeTest" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TarifficTakeHomeTest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to fa_icon('quote-left', text: "Quotes") , "/"  %></li>            
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote, html: {class: 'form-horizontal' }) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input  :author, required: true %>
  <%= f.input  :quote, as: :text, required: true%>
  <%= f.input  :mood, as: :select, collection: mood_select_options %>
  <%= f.input  :quote_source, as: :text %>

  <div class="actions">
  <center>
    <%= html_submit %>
  </center>    
  </div>
<% end %>

app/views/quotes/_list.html.erb
<p>
  <div class="row">
    <div class="col-md-4"><span class="pull-left"><%= smart_listing.pagination_per_page_links %></span></div>
    <div class="col-md-3">
        <%= link_to fa_icon('plus', text: 'New '), new_quote_path, :class => 'btn btn-primary'  %>
    </div>
    <div class="col-md-5">
      <%= smart_listing_controls_for(:quotes_smart_listing, {class: "form-inline text-right"}) do %>

      <span>
      Mood:
      <label><%= check_box_tag 'q[mood_in][]', 1, [ params[:q][:mood_in]].flatten.include?('1')%><%= content_tag "b", fa_icon("smile-o",  class: "text-info") %> Happy</label> |
      <label><%= check_box_tag 'q[mood_in][]', 2, [params[:q][:mood_in]].flatten.include?('2')%><%= content_tag "b",  fa_icon("meh-o",  class: "text-inverse") %> Meh</label> |
      <label><%= check_box_tag 'q[mood_in][]', 3, [params[:q][:mood_in]].flatten.include?('3')  %><%= content_tag "b",  fa_icon("frown-o", class: "text-danger") %>Unhappy</label>
      </span>
      <%= text_field_tag "q[quote_cont_or_author_cont_or_quote_source_cont]", params[:q]["quote_cont_or_author_cont_or_quote_source_cont"], class: "search form-control",  placeholder: "Search ..." %>
      <button type="submit"  class="btn btn-primary" data-disable-with="Please wait ..."><span class="fa fa-search"></span> Search</button>
      <a href="<%=  quotes_path %>" class="btn btn-info"  data-disable-with="Please wait ..."><span class="fa fa-refresh"></span> Reset</a>
      <% end %>
    </div>
  </div>
</p>


  <table class="table table-striped table-hover">
    <thead>
      <tr >
        <th><%= smart_listing.sortable "ID", :id %> </th>
        <th><%= smart_listing.sortable "Author", :author %> </th>
        <th><%= smart_listing.sortable "Quote", :quote %> </th>
        <th><%= smart_listing.sortable "Mood",  :mood %> </th>
        <th><%= smart_listing.sortable "QuoteSource",  :quote_source %> </th>
        <th><%= smart_listing.sortable "On twitter?",  :posted_to_twitter %> </th>
        <th><%= smart_listing.sortable "Updated at",  :updated_at %> </th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% if smart_listing.empty? %>
      <tr>
        <td colspan="1000">
          <p>
            <center>
              <h4>No items</h4>
            </center>
          </p>
        </td>
      </tr>
      <% else %>
        <% smart_listing.collection.each do |object| %>
          <tr >
            <%= smart_listing.render partial: 'quotes/quote', locals: {object: object} %>            
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<div class="row">
  <div class="col-md-12"><%= smart_listing.paginate %></div>
</div>

app/views/quotes/_quote.html.erb
<td><%= object.id %></td>
<td><%= object.author %></td>
<td><%= object.quote %></td>
<td><%= mood_display object.mood %></td>
<td><%= object.quote_source %></td>
<td><%= yesno object.posted_to_twitter %> </td>
<td><%= datetime_format object.updated_at %> </td>
<td class='actions'>
  <%= view_link('View', quote_path(object), 'btn-xs' )%>
  <%= edit_link('Edit', edit_quote_path(object), 'btn-xs') %>
  <%= trash_link('Delete', quote_path(object), 'btn-xs') %>
  <%= link_to fa_icon(:twitter, text: "Post to Twitter"), post_to_twitter_quote_path(object), class: 'btn btn-info btn-xs', method: :post, confirm: "Are you sure?" unless  object.posted_to_twitter%>

</td>

app/views/quotes/edit.html.erb
<div class="row" >
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class=" panel-heading">
      <div class="row">
        <div class="col-md-6">
          <h4 class="panel-title">Edit quote</h4>
        </div>
            
        <div class="col-md-6"> 
          <span class="pull-right">
            <%= view_link('View', quote_path(@quote), 'btn-xs' )%>
             <%= back_link('Back', quotes_path, 'btn-xs')%>
           </span>
        </div>
        </div>
      </div>
      <div class="panel-body">
           <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/quotes/index.html.erb
<div class="row" id="system-admin-accounts-container">
  <div class="col-md-12">
    <div class="panel panel-inverse">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6"> <h2>Quotes</h4></div>
          <div class="col-md-6"> 
            <span class="pull-right">
             <b>Mood counts:</b>
              <% Quote.mood_counts.each do |k,v|%>
                <%= mood_count_display(k,v) %>
              <% end %>
            </span>
          </div>
        </div>
        
      </div>
      <div class="panel-body">
        <%= smart_listing_render(:quotes_smart_listing) %>
      </div>
    </div>
  </div>
</div>

app/views/quotes/index.js.erb
<%= smart_listing_update(:quotes_smart_listing) %>

app/views/quotes/new.html.erb
<div class="row" >
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class=" panel-heading">
      <div class="row">
        <div class="col-md-6">
          <h4 class="panel-title">New quote</h4>
        </div>
            
        <div class="col-md-6"> 
          <span class="pull-right">
             <%= back_link('Back', quotes_path, 'btn-xs')%>
           </span>
        </div>
        </div>
      </div>
      <div class="panel-body">
           <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/quotes/show.html.erb
<div class="row" >
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class=" panel-heading">
      <div class="row">
        <div class="col-md-6">
          <h4 class="panel-title">Show quote</h4>
        </div>
            
        <div class="col-md-6"> 
          <span class="pull-right">
            <%= edit_link('Edit', edit_quote_path(@quote), 'btn-xs' )%>
             <%= link_to fa_icon(:twitter, text: "Post to Twitter"), post_to_twitter_quote_path(@quote), class: 'btn btn-info btn-xs', method: :post, confirm: "Are you sure?" unless  @quote.posted_to_twitter%>

             <%= back_link('Back', quotes_path, 'btn-xs')%>
           </span>
        </div>
        </div>
      </div>
      <div class="panel-body">       
  
          <p>
            <strong>Author:</strong>
            <%= @quote.author %>
          </p>
          <p>
            <strong>Quote:</strong>
            <%= @quote.quote %>
          </p>

          <p>
            <strong>Mood:</strong>
            <%= mood_display @quote.mood %>
          </p>
          <p>
            <strong>Posted to twitter:</strong>
            <%= yesno @quote.posted_to_twitter %>
          </p>
    

          <p>
            <strong>Quote source:</strong>
            <%= @quote.quote_source %>
          </p>

          <p>
            <strong>Processed quote:</strong>
            <%= @quote.processed_quote %>
          </p>

         <p>
            <strong>Created at:</strong>
            <%=datetime_format @quote.created_at %>
          </p>



         <p>
            <strong>Updated at:</strong>
            <%= datetime_format @quote.updated_at %>
          </p>
      </div>
    </div>
  </div>
</div>